// Cleans up a file generated by frequencyCounter.js
//
// Removes:
// 	- any word that has a cdCount of 1
//  - any word that is made up of all special characters.
//
// Changes:
// 	- don into don't
//  - couldn into couldn't
//  - wouldn into wouldn't
//  - didn into didn't
//  - iv into i've
//
// Usage: 
// node cleaner.js -i inFileName -o outFileName

var fs = require('fs');
var _ = require('underscore');

var argv = require('minimist')(process.argv.slice(2));

function merge( clean, key, data ){
	if (!clean[key]){
		clean[key] = data;
	} else {
		clean[key].freqCount += data.freqCount;
		clean[key].cdCount += data.cdCount;
	}
}

if ( !argv.i || !argv.o ){
	console.log("Missing parameter. Usage:");
	console.log("node stats.js -i inFileName -o outFileName");
} else {
	var inFile = argv.i,
		outFile = argv.o;

	var data = JSON.parse(fs.readFileSync( inFile ) );

	var keys = Object.keys(data);
	console.log("starting words: " + keys.length);

	var clean = {};

	var skipWords = [
		're',
		'll',
		've'
	];

	var replacer = [
		"didn",
		"wouldn",
		"couldn",
		"ain",
		"don",
		"hadn",
		"hasn",
		"isn",
		"mightn",
		"shouldn",
		"wasn",
		"wouldn"
	];

	var replacement = [
		"didn't",
		"wouldn't",
		"couldn't",
		"ain't",
		"don't",
		"hadn't",
		"hasn't",
		"isn't",
		"mightn't",
		"shouldn't",
		"wasn't",
		"wouldn't"
	];

	for ( var i = 0, len = keys.length; i < len; i++ ){
		var key = keys[i];

		var cleanKey = key;
		
		if  ( data[key].cdCount > 1 ){
			cleanKey = key
				.replace(/-/g,'')
				.replace(/–/g,'')
				.replace(/,/g,'')
				.replace(/'/,'');

			if ( 
				// Check for weird characters
				( !/\W/.test( cleanKey ) ) &&
				// check for one letter words 
				!(( cleanKey.length == 1) && ( ['a','i'].indexOf( cleanKey ) == -1 )) &&
				// check for skip words
				( skipWords.indexOf( cleanKey ) == -1 ) &&
				// check for numbers
				( !/^\d+$/.test( cleanKey ) )
				) {

				var rIndex = replacer.indexOf(cleanKey);
				if ( rIndex > -1 ){
					cleanKey = replacement[rIndex];
				}
				
				merge( clean, cleanKey, data[key] );
			} 

		}		
	}	

	console.log("valid words: " + Object.keys(clean).length);

	fs.writeFileSync( outFile, JSON.stringify( clean, null, 4 ) );
}